# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'MangopayDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MangopayDemo
  
  pod 'CFAlertViewController'

  target 'MangopayDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MangopayDemoUITests' do
    # Pods for testing
  end

end
