# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - name: Print a random message
        run: |
          messages=("Hello, world!" "Keep going!" "Swift is awesome!" "You got this!" "Make it work, make it right, make it fast.")
          RANDOM_INDEX=$((RANDOM % ${#messages[@]}))
          echo "🎉 Random Message: ${messages[$RANDOM_INDEX]}"
